const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const source=fs.readFileSync('content.js','utf8');
function harness(){const state={scheduleViewMode:'gameRatings',settingsOpen:true,gameRatingFilters:{genre:'전체',search:'',sort:'recent',range:'',visible:5},shadow:{querySelector:()=>({focus(){}})}};const ctx=vm.createContext({state,api:{runtime:{getURL:p=>'/'+p}},CALENDAR_ICON_URL:'calendar.svg',GAMEPAD_ICON_URL:'gamepad.svg',closePopover(){},render(){ctx.renders=(ctx.renders||0)+1}});vm.runInContext(source.slice(source.indexOf('  const GAME_RATING_PREVIEW'),source.indexOf('  function gameRatingsHtml')),ctx);for(const name of ['gameRatingsHtml','lolLogToggleHtml','switchScheduleViewMode','escapeHtml']){const start=source.indexOf('  '+(name==='switchScheduleViewMode'?'async ':'')+'function '+name+'('),body=source.slice(start),end=/\r?\n  }\r?\n/.exec(body);vm.runInContext(body.slice(0,end.index+end[0].length),ctx)}return ctx}
test('ranked shelf shows highest scores first and expands five rows to eight',()=>{const h=harness();let html=h.gameRatingsHtml();assert.equal((html.match(/class="cs-rating-row"/g)||[]).length,5);const list=html.slice(html.indexOf('class="cs-rating-list"'));assert.ok(list.indexOf('클레르 옵스퀴르')<list.indexOf('Hades'));assert.ok(list.indexOf('Hades')<list.indexOf('스테퍼 레트로'));assert.ok(html.includes('시안용 임의 데이터'));h.state.gameRatingFilters.visible=10;assert.equal((h.gameRatingsHtml().match(/class="cs-rating-row"/g)||[]).length,8)});
test('search filters rankings while preserving global rank and resets empty results',()=>{const h=harness();h.state.gameRatingFilters.search='스테퍼';const html=h.gameRatingsHtml();assert.equal((html.match(/class="cs-rating-row"/g)||[]).length,1);assert.ok(html.includes('cs-rating-index">03'));h.state.gameRatingFilters.search='不存在';assert.ok(h.gameRatingsHtml().includes('cs-rating-reset'))});
test('selection exposes matching poster, score and active ranking row',()=>{const h=harness();h.state.gameRatingFilters.selectedId=2;const html=h.gameRatingsHtml();assert.match(html,/id="cs-rating-dot-2"[^>]*aria-pressed="true"/);const aside=html.slice(html.indexOf('<aside'));assert.ok(aside.includes('data-game-poster-query=\"Clair Obscur Expedition 33\"'));assert.ok(aside.includes('145'));assert.equal(html.includes('cs-rating-scatter'),false);assert.equal(html.includes('max="100"'),false);assert.ok(html.includes('cs-rating-recent'))});
test('validated YouTube ID replaces poster and invalid ID falls back to poster',()=>{const h=harness();vm.runInContext('GAME_RATING_PREVIEW[0].youtubeId="abcdefghijk"',h);assert.ok(h.gameRatingsHtml().includes('https://www.youtube-nocookie.com/embed/abcdefghijk'));vm.runInContext('GAME_RATING_PREVIEW[0].youtubeId="https://evil.test/"',h);assert.equal(h.gameRatingsHtml().includes('<iframe'),false);assert.ok(h.gameRatingsHtml().includes('data-game-poster-query=\"Staffer Retro\"'))});
test('game ratings stay hidden while schedule and LoL modes retain switching',async()=>{const h=harness();assert.equal((h.lolLogToggleHtml().match(/data-schedule-mode=/g)||[]).length,2);assert.equal(h.lolLogToggleHtml().includes('gameRatings'),false);for(const mode of ['schedule','lolMatchLogs']){await h.switchScheduleViewMode({dataset:{scheduleMode:mode}});assert.equal(h.state.scheduleViewMode,mode);assert.equal(h.state.settingsOpen,false)}const before=h.renders;await h.switchScheduleViewMode({dataset:{scheduleMode:'gameRatings'}});assert.equal(h.renders,before);assert.equal(h.state.scheduleViewMode,'lolMatchLogs')});

test('score collections retain unbounded scores and include fractional scores at boundaries',()=>{const h=harness();h.state.gameRatingFilters.range='0';let html=h.gameRatingsHtml();assert.equal((html.match(/class="cs-rating-row"/g)||[]).length,2);assert.ok(html.includes('100점 이상 · 스코어'));assert.ok(html.includes('cs-rating-range-all'));vm.runInContext('GAME_RATING_PREVIEW[0].score=89.5',h);h.state.gameRatingFilters.range='2';html=h.gameRatingsHtml();assert.equal((html.match(/class="cs-rating-row"/g)||[]).length,3);assert.ok(html.includes('89.5'));vm.runInContext('GAME_RATING_PREVIEW[0].score=90',h);h.state.gameRatingFilters.range='1';assert.equal((h.gameRatingsHtml().match(/class="cs-rating-row"/g)||[]).length,1)});
